packages:
  - 'packages/*'
  - 'apps/*'
  - 'extensions/taiji/*'
  - 'extensions/universal/*'
  - 'extensions/shared/*'
overrides:
  '@earendil-works/pi-coding-agent': 1.0.0
  '@earendil-works/pi-ai': 1.0.0
  '@earendil-works/pi-tui': 1.0.0
  '@earendil-works/pi-agent-core': 1.0.0
onlyBuiltDependencies:
  - esbuild
  - electron
  - node-pty
  - vue-demi
